# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0002_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='create',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 20, 10, 8, 41, 929000, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='project',
            name='owner',
            field=models.CharField(default='', max_length=30),
        ),
    ]
