# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-21 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0004_auto_20160320_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
