# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0005_auto_20160321_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='', max_length=80)),
                ('short_name', models.CharField(default='', max_length=20)),
                ('server_path', models.CharField(default='', max_length=255)),
                ('local_path', models.CharField(blank=True, default='', max_length=255)),
                ('crash_path', models.CharField(default='', max_length=255)),
                ('use_server', models.BooleanField(default=False)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tbd.Project', verbose_name='the related project')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='build',
            unique_together=set([('version', 'project')]),
        ),
    ]
