# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0006_auto_20160324_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('ip', models.GenericIPAddressField(default='', protocol='IPv4')),
                ('mac', models.CharField(default='', max_length=12)),
            ],
        ),
    ]
