# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0007_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=80, unique=True)),
                ('platform', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
