# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0008_testcase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(default='', max_length=255, unique=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tbd.Build', verbose_name='the related build')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tbd.Host', verbose_name='the related host')),
                ('testcase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tbd.TestCase', verbose_name='the related testcase')),
            ],
        ),
    ]
