# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0009_crash'),
    ]

    operations = [
        migrations.AddField(
            model_name='crash',
            name='category',
            field=models.CharField(choices=[('UN', 'Undetermined Issue'), ('IN', 'Invalid Issue'), ('WD', 'Withdraw Issue'), ('CN', 'CNSS Issue'), ('NC', 'Non-CNSS Issue')], default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='platform',
            field=models.CharField(choices=[('PH', 'Phoenix XML'), ('VE', 'Vega XML'), ('GA', 'Garnet XML'), ('WP', 'WPA Perl')], default='', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together=set([('name', 'platform')]),
        ),
    ]
