# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0011_auto_20160331_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='JIRA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_id', models.CharField(default='', max_length=20, unique=True)),
                ('category', models.CharField(choices=[('OP', 'Open Issue'), ('IN', 'Invalid Issue'), ('WD', 'Withdraw Issue'), ('CN', 'CNSS Issue'), ('NC', 'Non-CNSS Issue')], default='OP', max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='crash',
            name='category',
        ),
        migrations.AddField(
            model_name='crash',
            name='jira',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tbd.JIRA', verbose_name='the related JIRA'),
        ),
    ]
