# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0012_auto_20160401_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tbd.Project', verbose_name='the related project'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tbd.Project', verbose_name='the related project'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set([('project', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together=set([('project', 'name', 'platform')]),
        ),
    ]
