# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-18 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0013_auto_20160405_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='platform',
            field=models.CharField(choices=[('', '--select testcase--'), ('PH', 'Phoenix XML'), ('VE', 'Vega XML'), ('GA', 'Garnet XML'), ('WP', 'WPA Perl')], default='', max_length=2),
        ),
    ]
