# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0014_auto_20160418_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_attr',
            field=models.TextField(default=''),
        ),
    ]
