# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 02:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0015_project__attr'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 8, 24, 2, 55, 1, 627000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
