# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-25 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0017_auto_20160825_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='test_hours',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='platform',
            field=models.CharField(choices=[('', 'N/A'), ('PHO', 'Phoenix XML'), ('VEG', 'Vega XML'), ('GAR', 'Garnet XML'), ('WPA', 'WPA Perl'), ('PAT', 'PAT Python')], default='', max_length=3),
        ),
    ]
