# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-26 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0019_auto_20160826_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crash',
            name='jira',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.PROTECT, to='tbd.JIRA', verbose_name='the related JIRA'),
            preserve_default=False,
        ),
    ]
