# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0022_auto_20160829_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='ip',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='host',
            name='mac',
            field=models.CharField(default='', max_length=17),
        ),
    ]
