# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 10:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0023_auto_20160831_0403'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='last_update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 9, 1, 10, 12, 24, 710000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
