# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-11-04 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0026_auto_20161104_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jira',
            name='cr_id',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
