# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-03-03 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0027_auto_20161104_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='short_name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
