# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-24 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0028_auto_20170303_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testbuild', models.CharField(default='', max_length=255)),
                ('testdut', models.CharField(default='', max_length=255)),
                ('testdate', models.DateField(auto_now_add=True)),
                ('testtime', models.IntegerField(default=0)),
            ],
        ),
    ]
