# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-26 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0029_testtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtime',
            old_name='testtime',
            new_name='testcount',
        ),
        migrations.AddField(
            model_name='testtime',
            name='timesection',
            field=models.IntegerField(default=0),
        ),
    ]
