# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0029_testtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testtime',
            old_name='testtime',
            new_name='testcount',
        ),
        migrations.AddField(
            model_name='testtime',
            name='timesection',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='testtime',
            name='testbuild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbd.Build'),
        ),
        migrations.AlterField(
            model_name='testtime',
            name='testdut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbd.Host'),
        ),
        migrations.AlterUniqueTogether(
            name='testtime',
            unique_together=set([('testbuild', 'testdut', 'testdate', 'timesection')]),
        ),
    ]
