# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-26 09:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0030_auto_20180326_1655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testtime',
            unique_together=set([('testbuild', 'testdut', 'testdate', 'timesection')]),
        ),
    ]
