# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-03-27 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbd', '0031_auto_20180326_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtime',
            name='testbuild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbd.Build'),
        ),
        migrations.AlterField(
            model_name='testtime',
            name='testdut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tbd.Host'),
        ),
    ]
