# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('WPA2', 'WPA2_PSK'), ('OPEN', 'OPEN'), ('WPA', 'WPA_PSK'), ('WEP', 'WEP')], max_length=4)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
