# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-07 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_auto_20180407_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
