# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0007_auto_20180423_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
