# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 01:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_ap_ip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ap',
            old_name='aging',
            new_name='ping_aging',
        ),
    ]
