# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-24 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_auto_20180424_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='ap',
            name='connect_aging',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ap',
            name='scan_aging',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
