# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-26 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_auto_20180424_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap',
            name='owner',
            field=models.CharField(max_length=30),
        ),
    ]
